/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package net.vnleng.generator.gui.frames;

/**
 *
 * @author gabri
 */
public class FBGenerator extends javax.swing.JInternalFrame {

    /**
     * Creates new form FBGenerator
     */
    public FBGenerator() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        PanelFBGen = new javax.swing.JPanel();
        FBNameLabel = new javax.swing.JLabel();
        FBNameTF = new javax.swing.JTextField();
        ScrollPaneInput = new javax.swing.JScrollPane();
        ListaVarInput = new javax.swing.JList<>();
        VarInputLabel = new javax.swing.JLabel();
        ScrollPaneConst = new javax.swing.JScrollPane();
        ListaVarConst = new javax.swing.JList<>();
        VarConstLabel = new javax.swing.JLabel();
        FBReferenceTF = new javax.swing.JTextField();
        FBReferenceLabel = new javax.swing.JLabel();
        LinkDB = new javax.swing.JButton();

        setIconifiable(true);
        setTitle("Definizione Funzione");

        PanelFBGen.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));

        FBNameLabel.setText("Nome FC:");

        ListaVarInput.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        ScrollPaneInput.setViewportView(ListaVarInput);

        VarInputLabel.setText("Variabili Input:");

        ListaVarConst.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        ScrollPaneConst.setViewportView(ListaVarConst);

        VarConstLabel.setText("Variabili Costanti:");

        FBReferenceLabel.setText("FC/FB Da eseguire:");

        LinkDB.setText("Associa elementi");

        javax.swing.GroupLayout PanelFBGenLayout = new javax.swing.GroupLayout(PanelFBGen);
        PanelFBGen.setLayout(PanelFBGenLayout);
        PanelFBGenLayout.setHorizontalGroup(
            PanelFBGenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelFBGenLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(PanelFBGenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(LinkDB, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(ScrollPaneInput)
                    .addComponent(ScrollPaneConst)
                    .addGroup(PanelFBGenLayout.createSequentialGroup()
                        .addComponent(FBReferenceLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(FBReferenceTF, javax.swing.GroupLayout.DEFAULT_SIZE, 169, Short.MAX_VALUE))
                    .addGroup(PanelFBGenLayout.createSequentialGroup()
                        .addComponent(FBNameLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(FBNameTF))
                    .addGroup(PanelFBGenLayout.createSequentialGroup()
                        .addGroup(PanelFBGenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(VarInputLabel)
                            .addComponent(VarConstLabel))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        PanelFBGenLayout.setVerticalGroup(
            PanelFBGenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelFBGenLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(PanelFBGenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(FBNameLabel)
                    .addComponent(FBNameTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(VarInputLabel)
                .addGap(4, 4, 4)
                .addComponent(ScrollPaneInput, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(VarConstLabel)
                .addGap(4, 4, 4)
                .addComponent(ScrollPaneConst, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(PanelFBGenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(FBReferenceTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(FBReferenceLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(LinkDB)
                .addContainerGap(47, Short.MAX_VALUE))
        );

        getContentPane().add(PanelFBGen, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel FBNameLabel;
    private javax.swing.JTextField FBNameTF;
    private javax.swing.JLabel FBReferenceLabel;
    private javax.swing.JTextField FBReferenceTF;
    private javax.swing.JButton LinkDB;
    private javax.swing.JList<String> ListaVarConst;
    private javax.swing.JList<String> ListaVarInput;
    private javax.swing.JPanel PanelFBGen;
    private javax.swing.JScrollPane ScrollPaneConst;
    private javax.swing.JScrollPane ScrollPaneInput;
    private javax.swing.JLabel VarConstLabel;
    private javax.swing.JLabel VarInputLabel;
    // End of variables declaration//GEN-END:variables
}
