/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package net.vnleng.generator.gui.frames;

import net.vnleng.generator.data.ProjectResource;
import net.vnleng.generator.data.ints.ResourceType;
import net.vnleng.generator.gui.renders.ProjectResourceRender;
import java.awt.Dimension;
import java.awt.Image;
import java.awt.Point;
import java.awt.Toolkit;
import java.awt.datatransfer.Clipboard;
import java.awt.datatransfer.DataFlavor;
import java.awt.datatransfer.UnsupportedFlavorException;
import java.awt.event.KeyEvent;
import java.io.IOException;
import javax.swing.DefaultListModel;
import javax.swing.ImageIcon;

/**
 *
 * @author gabri
 */
public class ProjectDefinitions extends javax.swing.JInternalFrame {

    private final ProjectResourceRender prr = new ProjectResourceRender();

    /**
     * Creates new form ProjectDefinitions
     */
    public ProjectDefinitions() {
        initComponents();
        AddResource.setComponentPopupMenu(AddContextMenu);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        PopupAddFBFC = new javax.swing.JDialog();
        ElementNameLabel = new javax.swing.JLabel();
        ResourceNameTF = new javax.swing.JTextField();
        FBType = new javax.swing.JRadioButton();
        FCType = new javax.swing.JRadioButton();
        ConfirmAddResource = new javax.swing.JButton();
        DiscardAddResource = new javax.swing.JButton();
        ResourceTypeBtnGroup = new javax.swing.ButtonGroup();
        AddContextMenu = new javax.swing.JPopupMenu();
        FBFCAdder = new javax.swing.JMenuItem();
        DBAdder = new javax.swing.JMenuItem();
        PanelDefsProj = new javax.swing.JPanel();
        ScrollPaneDefsList = new javax.swing.JScrollPane();
        DefsList = new javax.swing.JList<>();
        DefsListDescription = new javax.swing.JLabel();
        AddResource = new javax.swing.JButton();
        RemoveResource = new javax.swing.JButton();

        PopupAddFBFC.setTitle("Aggiungi Risorsa");
        PopupAddFBFC.setAlwaysOnTop(true);
        PopupAddFBFC.setMinimumSize(new java.awt.Dimension(400, 98));
        PopupAddFBFC.setModal(true);
        PopupAddFBFC.setName("AddResourceDialog"); // NOI18N
        PopupAddFBFC.setResizable(false);
        PopupAddFBFC.setSize(new java.awt.Dimension(400, 120));
        PopupAddFBFC.setType(java.awt.Window.Type.UTILITY);

        ElementNameLabel.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        ElementNameLabel.setText("Nome elemento:");

        ResourceNameTF.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        ResourceNameTF.setText("NomeFunzione");

        ResourceTypeBtnGroup.add(FBType);
        FBType.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        FBType.setText("Function Block (FB)");

        ResourceTypeBtnGroup.add(FCType);
        FCType.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        FCType.setSelected(true);
        FCType.setText("Function (FC)");

        ConfirmAddResource.setText("Aggiungi");
        ConfirmAddResource.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ConfirmAddResourceMouseClicked(evt);
            }
        });

        DiscardAddResource.setText("Annulla");
        DiscardAddResource.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                DiscardAddResourceMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout PopupAddFBFCLayout = new javax.swing.GroupLayout(PopupAddFBFC.getContentPane());
        PopupAddFBFC.getContentPane().setLayout(PopupAddFBFCLayout);
        PopupAddFBFCLayout.setHorizontalGroup(
            PopupAddFBFCLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PopupAddFBFCLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(PopupAddFBFCLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(PopupAddFBFCLayout.createSequentialGroup()
                        .addComponent(DiscardAddResource)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(ConfirmAddResource, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, PopupAddFBFCLayout.createSequentialGroup()
                        .addComponent(ElementNameLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(PopupAddFBFCLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(ResourceNameTF, javax.swing.GroupLayout.PREFERRED_SIZE, 273, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(PopupAddFBFCLayout.createSequentialGroup()
                                .addComponent(FCType)
                                .addGap(18, 18, 18)
                                .addComponent(FBType)))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        PopupAddFBFCLayout.setVerticalGroup(
            PopupAddFBFCLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PopupAddFBFCLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(PopupAddFBFCLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ElementNameLabel)
                    .addComponent(ResourceNameTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(6, 6, 6)
                .addGroup(PopupAddFBFCLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(FCType)
                    .addComponent(FBType))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(PopupAddFBFCLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ConfirmAddResource)
                    .addComponent(DiscardAddResource))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        FBFCAdder.setText("Aggiungi FC/FB");
        FBFCAdder.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FBFCAdderActionPerformed(evt);
            }
        });
        AddContextMenu.add(FBFCAdder);

        DBAdder.setText("Definisci DB");
        ImageIcon DBIcon = new ImageIcon(new ImageIcon(getClass().getResource("/net/vnleng/generator/resources/database.png")).getImage().getScaledInstance(20, 20, Image.SCALE_DEFAULT));
        DBAdder.setIcon(DBIcon);
        AddContextMenu.add(DBAdder);

        PanelDefsProj.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));

        DefsList.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        DefsList.setModel(new DefaultListModel());
        DefsList.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        DefsList.setToolTipText("<html>\nFunzioni possibili:\n<ul>\n<li>Doppio click per cambiare tra FB e FC</li>\n<li>Incollare valori da lista di Excel</li>\n</ul>\n</html>");
        DefsList.setCellRenderer(prr);
        DefsList.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        DefsList.setName(""); // NOI18N
        DefsList.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                DefsListMouseClicked(evt);
            }
        });
        DefsList.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                DefsListKeyPressed(evt);
            }
        });
        ScrollPaneDefsList.setViewportView(DefsList);

        DefsListDescription.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        DefsListDescription.setText("Definizioni nel Progetto:");

        AddResource.setText("Aggiungi");
        AddResource.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddResourceActionPerformed(evt);
            }
        });

        RemoveResource.setText("Rimuovi");
        RemoveResource.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                RemoveResourceMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout PanelDefsProjLayout = new javax.swing.GroupLayout(PanelDefsProj);
        PanelDefsProj.setLayout(PanelDefsProjLayout);
        PanelDefsProjLayout.setHorizontalGroup(
            PanelDefsProjLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelDefsProjLayout.createSequentialGroup()
                .addGap(8, 8, 8)
                .addComponent(AddResource)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(RemoveResource)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelDefsProjLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(ScrollPaneDefsList, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(PanelDefsProjLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(DefsListDescription)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        PanelDefsProjLayout.setVerticalGroup(
            PanelDefsProjLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelDefsProjLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(DefsListDescription)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ScrollPaneDefsList, javax.swing.GroupLayout.DEFAULT_SIZE, 171, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(PanelDefsProjLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(AddResource)
                    .addComponent(RemoveResource))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        getContentPane().add(PanelDefsProj, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void DefsListMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_DefsListMouseClicked
        // TODO add your handling code here:
        if (evt.getClickCount() > 1 && !DefsList.isSelectionEmpty()) {
            ProjectResource selectedValue = DefsList.getSelectedValue();
            if (selectedValue.getType() == ResourceType.Function) {
                //selectedValue.setType(ResourceType.FunctionBlock);
            } else {
                //selectedValue.setType(ResourceType.Function);
            }
            DefsList.repaint();
        }
    }//GEN-LAST:event_DefsListMouseClicked

    private void DefsListKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_DefsListKeyPressed
        // TODO add your handling code here:
        if (evt.isControlDown() && evt.getKeyCode() == KeyEvent.VK_V) {
            try {
                Clipboard clipboard = Toolkit.getDefaultToolkit().getSystemClipboard();
                String data = (String) clipboard.getData(DataFlavor.stringFlavor);
                String[] rows = data.replaceAll("\r\n", "\n").replaceAll("</html>", "").split("\n");
                for (String row : rows) {
                    String content = row.split("\t")[0];
                    if (!content.isBlank() && content.trim().length() > 0) {
                        //addElementToResourceList(new ProjectResource(content, ResourceType.Function));
                    }
                }
            } catch (UnsupportedFlavorException | IOException ex) {
            }
        }
    }//GEN-LAST:event_DefsListKeyPressed

    private void RemoveResourceMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_RemoveResourceMouseClicked
        // TODO add your handling code here:
        if (!DefsList.isSelectionEmpty()) {
            DefaultListModel<ProjectResource> pr_list = (DefaultListModel) (DefsList.getModel());
            pr_list.removeElementAt(DefsList.getSelectedIndex());
            DefsList.setModel(pr_list);
        }
    }//GEN-LAST:event_RemoveResourceMouseClicked

    private void ConfirmAddResourceMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ConfirmAddResourceMouseClicked
        // TODO add your handling code here:
        String name = ResourceNameTF.getText();
        if ("".equals(name.trim())) {
            PopupAddFBFC.setVisible(false);
            return;
        }
        ResourceType rt = ResourceType.Function;
        if (FBType.isSelected()) {
            rt = ResourceType.FunctionBlock;
        }
        //addElementToResourceList(new ProjectResource(name, rt));
    }//GEN-LAST:event_ConfirmAddResourceMouseClicked

    private void DiscardAddResourceMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_DiscardAddResourceMouseClicked
        // TODO add your handling code here:
        PopupAddFBFC.setVisible(false);
    }//GEN-LAST:event_DiscardAddResourceMouseClicked

    private void FBFCAdderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FBFCAdderActionPerformed
        // TODO add your handling code here:
        PopupAddFBFC.setSize(new Dimension(392, 98));
        PopupAddFBFC.pack();
        PopupAddFBFC.setLocation(new Point((this.getWidth() + 392) / 2, (this.getHeight() + 98) / 2));
        PopupAddFBFC.setVisible(true);
    }//GEN-LAST:event_FBFCAdderActionPerformed

    private void AddResourceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddResourceActionPerformed
       AddResource.getComponentPopupMenu().show(AddResource, 0, 0);
    }//GEN-LAST:event_AddResourceActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPopupMenu AddContextMenu;
    private javax.swing.JButton AddResource;
    private javax.swing.JButton ConfirmAddResource;
    private javax.swing.JMenuItem DBAdder;
    private javax.swing.JList<ProjectResource> DefsList;
    private javax.swing.JLabel DefsListDescription;
    private javax.swing.JButton DiscardAddResource;
    private javax.swing.JLabel ElementNameLabel;
    private javax.swing.JMenuItem FBFCAdder;
    private javax.swing.JRadioButton FBType;
    private javax.swing.JRadioButton FCType;
    private javax.swing.JPanel PanelDefsProj;
    private javax.swing.JDialog PopupAddFBFC;
    private javax.swing.JButton RemoveResource;
    private javax.swing.JTextField ResourceNameTF;
    private javax.swing.ButtonGroup ResourceTypeBtnGroup;
    private javax.swing.JScrollPane ScrollPaneDefsList;
    // End of variables declaration//GEN-END:variables

    private void addElementToResourceList(ProjectResource pr) {
        DefaultListModel<ProjectResource> pr_list = (DefaultListModel) (DefsList.getModel());
        pr_list.addElement(pr);
        DefsList.setModel(pr_list);
    }
}
