/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package net.vnleng.generator.gui.panels.content;

import java.util.ResourceBundle;
import net.vnleng.generator.data.ints.ResourceType;
import net.vnleng.generator.data.scl.ints.FunctionResource;
import net.vnleng.generator.data.shared.SharedData;
import net.vnleng.generator.resources.TextResources;

/**
 *
 * @author gabri
 */
public class FunctionDefinitionPanel extends javax.swing.JPanel {

    private final ResourceBundle TXTBundle;
    private final SharedData data;
    private final ResourceType resType;
    private final FunctionResource funRes;

    /**
     * Creates new form FunctionDefinitionPanel
     */
    public FunctionDefinitionPanel(SharedData data, ResourceType rt, FunctionResource fr) {
        this.data = data;
        this.resType = rt;
        this.funRes = fr;
        TXTBundle = TextResources.GUITextBundle;
        initComponents();
        initPanes();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        MainTabbedPane = new javax.swing.JTabbedPane();
        OptionsPane = new javax.swing.JPanel();
        SaveFunctionBtn = new javax.swing.JButton();
        CancelEditBtn = new javax.swing.JButton();

        setLayout(new java.awt.BorderLayout());

        MainTabbedPane.setTabPlacement(javax.swing.JTabbedPane.LEFT);
        MainTabbedPane.setToolTipText("");
        add(MainTabbedPane, java.awt.BorderLayout.CENTER);

        SaveFunctionBtn.setText("jButton1");
        SaveFunctionBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SaveFunctionBtnActionPerformed(evt);
            }
        });
        OptionsPane.add(SaveFunctionBtn);

        CancelEditBtn.setText("jButton1");
        OptionsPane.add(CancelEditBtn);

        add(OptionsPane, java.awt.BorderLayout.PAGE_END);
    }// </editor-fold>//GEN-END:initComponents

    private void SaveFunctionBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SaveFunctionBtnActionPerformed
        // TODO add your handling code here:
        saveFunction();
    }//GEN-LAST:event_SaveFunctionBtnActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton CancelEditBtn;
    private javax.swing.JTabbedPane MainTabbedPane;
    private javax.swing.JPanel OptionsPane;
    private javax.swing.JButton SaveFunctionBtn;
    // End of variables declaration//GEN-END:variables

    private void initPanes() {
        switch (resType) {
            case Function:
            case FunctionBlock: {
                VariableTableCreator vtcIN = new VariableTableCreator("Input");
                MainTabbedPane.addTab("IN", vtcIN);
                VariableTableCreator vtcOUT = new VariableTableCreator("Output");
                MainTabbedPane.addTab("OUT", vtcOUT);
                VariableTableCreator vtcINOUT = new VariableTableCreator("Input/Output");
                MainTabbedPane.addTab("INOUT", vtcINOUT);
                if (resType.equals(ResourceType.FunctionBlock)) {
                    VariableTableCreator vtcSTATIC = new VariableTableCreator("Constant");
                    MainTabbedPane.addTab("CONST", vtcSTATIC);
                }
                VariableTableCreator vtcTEMP = new VariableTableCreator("Temp");
                MainTabbedPane.addTab("TEMP", vtcTEMP);
            }
            break;
            case DataBlock: {
                VariableTableCreator vtcSTATIC = new VariableTableCreator("Static");
                MainTabbedPane.addTab("STATIC", vtcSTATIC);
                break;
            }
            case FunctionInstance: {
                if (funRes != null) {
                    VariableTableCreator vtcIN = new VariableTableCreator("Input");
                    MainTabbedPane.addTab("IN", vtcIN);
                    VariableTableCreator vtcOUT = new VariableTableCreator("Output");
                    MainTabbedPane.addTab("OUT", vtcOUT);
                    VariableTableCreator vtcINOUT = new VariableTableCreator("Input/Output");
                    MainTabbedPane.addTab("INOUT", vtcINOUT);
                    if (funRes.getType().equals(ResourceType.FunctionBlock)) {
                        VariableTableCreator vtcSTATIC = new VariableTableCreator("Constant");
                        MainTabbedPane.addTab("CONST", vtcSTATIC);
                    }
                    VariableTableCreator vtcTEMP = new VariableTableCreator("Temp");
                    MainTabbedPane.addTab("TEMP", vtcTEMP);
                }
                break;
            }
            default:
                break;
        }
    }

    private void saveFunction() {
        
    }
}
