/*
 * Copyright (C) 2025 gabri
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program.  If not, see <http://www.gnu.org/licenses/>.
 */
package net.vnleng.generator.gui.panels.content.vars;

import java.awt.event.KeyEvent;
import java.util.ResourceBundle;
import javax.swing.JTextField;
import net.vnleng.generator.commons.events.CloseRequestListener;
import net.vnleng.generator.data.ints.var.Variable;
import net.vnleng.generator.data.ints.var.VariableType;
import net.vnleng.generator.gui.ints.ClosableFrame;
import net.vnleng.generator.resources.TextResources;

/**
 *
 * @author gabri
 */
public class StringVariableDefinition extends javax.swing.JPanel implements ClosableFrame {

    private final ResourceBundle TXTBundle = TextResources.GUITextBundle;
    private final Variable v;
    private CloseRequestListener listener;

    /**
     * Creates new form CustomVariableDefinition
     */
    public StringVariableDefinition(Variable v) {
        this.v = v;
        initComponents();
        if (v.getType() == VariableType.WString) {
            this.StringLabel.setText("WString[");
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        UpperSize = new javax.swing.JTextField();
        OfLabel = new javax.swing.JLabel();
        ApplyBtn = new javax.swing.JButton();
        UndoBtn = new javax.swing.JButton();
        StringLabel = new javax.swing.JLabel();

        UpperSize.setText("5");
        UpperSize.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                UpperSizeKeyPressed(evt);
            }
        });

        OfLabel.setText("]");

        ApplyBtn.setText(TXTBundle.getString("Apply"));
        ApplyBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ApplyBtnActionPerformed(evt);
            }
        });

        UndoBtn.setText(TXTBundle.getString("Undo"));
        UndoBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UndoBtnActionPerformed(evt);
            }
        });

        StringLabel.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        StringLabel.setText("String [");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(StringLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(UpperSize, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(OfLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 13, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(UndoBtn)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(ApplyBtn)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(StringLabel)
                    .addComponent(UpperSize, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(OfLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ApplyBtn)
                    .addComponent(UndoBtn))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void UndoBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UndoBtnActionPerformed
        if (listener != null) {
            listener.onCloseRequest();
        }
    }//GEN-LAST:event_UndoBtnActionPerformed

    private void ApplyBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ApplyBtnActionPerformed
        execute();
    }//GEN-LAST:event_ApplyBtnActionPerformed

    private void UpperSizeKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_UpperSizeKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            execute();
        }
    }//GEN-LAST:event_UpperSizeKeyPressed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ApplyBtn;
    private javax.swing.JLabel OfLabel;
    private javax.swing.JLabel StringLabel;
    private javax.swing.JButton UndoBtn;
    private javax.swing.JTextField UpperSize;
    // End of variables declaration//GEN-END:variables

    private int convertToNumber(JTextField jtf) {
        String text = jtf.getText();
        if (text == null || text.isBlank()) {
            return 0;
        }
        try {
            return Integer.parseInt(text);
        } catch (NumberFormatException nfe) {
            return 0;
        }
    }

    private void execute() {
        int upper = convertToNumber(UpperSize);
        if (upper < 1) {
            return;
        }
        v.getModifier().setIsList(true, upper);
        if (listener != null) {
            listener.onCloseRequest();
        }
    }

    @Override
    public void addCloseRequestListener(CloseRequestListener crl) {
        this.listener = crl;
    }

    @Override
    public void removeCloseRequestListener(CloseRequestListener crl) {
        this.listener = null;
    }
}
