/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package net.vnleng.generator.gui.panels.content.vars;

import java.awt.Dialog;
import java.awt.Point;
import java.awt.Rectangle;
import java.awt.event.ComponentEvent;
import java.awt.event.ComponentListener;
import java.awt.event.KeyEvent;
import java.awt.event.MouseEvent;
import java.util.List;
import java.util.ResourceBundle;
import javax.swing.JDialog;
import javax.swing.event.TableModelEvent;
import net.vnleng.generator.commons.TextToolHandler;
import net.vnleng.generator.data.ints.res.PackType;
import net.vnleng.generator.data.ints.res.VariablePack;
import net.vnleng.generator.data.ints.var.Variable;
import net.vnleng.generator.data.ints.var.VariableType;
import net.vnleng.generator.gui.ints.ClosableFrame;
import net.vnleng.generator.gui.renders.table.TableRow;
import net.vnleng.generator.gui.renders.table.VariableTableRender;
import net.vnleng.generator.gui.renders.table.CustomTableColumn;
import net.vnleng.generator.resources.TextResources;

/**
 *
 * @author gabri
 */
public class VariableTableCreator extends javax.swing.JPanel {

    private final ResourceBundle TXTBundle;
    private final String varLabelString;
    private final VariablePack vars;
    private VariableTableRender vtr;
    private final boolean contentEditable;

    public VariableTableCreator(String label, VariablePack vars, boolean editable) {
        this.vars = vars;
        this.contentEditable = editable;
        //Set the text bundle
        TXTBundle = TextResources.GUITextBundle;
        //String 
        varLabelString = label;
        initComponents();
        initVariableTableModel();
    }

    /**
     * Creates new form FunctionCreator
     *
     * @param label Title inside of this container set next to the buttons.
     */
    public VariableTableCreator(String label, PackType pt, boolean editable) {
        this.vars = new VariablePack(pt);
        this.contentEditable = editable;
        //Set the text bundle
        TXTBundle = TextResources.GUITextBundle;
        //String 
        varLabelString = label;
        initComponents();
        initVariableTableModel();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        TableEditorPopUp = new javax.swing.JPopupMenu();
        MoveUpBtn = new javax.swing.JMenuItem();
        MoveDownBtn = new javax.swing.JMenuItem();
        PopUpSep = new javax.swing.JPopupMenu.Separator();
        DuplicateBtn = new javax.swing.JMenuItem();
        RemoveBtn = new javax.swing.JMenuItem();
        PanelOptionsIN = new javax.swing.JPanel();
        VarLabel = new javax.swing.JLabel();
        AddRow = new javax.swing.JButton();
        DeleteRow = new javax.swing.JButton();
        TableScrollPane = new javax.swing.JScrollPane();
        VarTable = new javax.swing.JTable();

        MoveUpBtn.setText(TXTBundle.getString("MoveUp")
        );
        MoveUpBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MoveUpBtnActionPerformed(evt);
            }
        });
        TableEditorPopUp.add(MoveUpBtn);

        MoveDownBtn.setText(TXTBundle.getString("MoveDown"));
        MoveDownBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MoveDownBtnActionPerformed(evt);
            }
        });
        TableEditorPopUp.add(MoveDownBtn);
        TableEditorPopUp.add(PopUpSep);

        DuplicateBtn.setText(TXTBundle.getString("Duplicate"));
        DuplicateBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DuplicateBtnActionPerformed(evt);
            }
        });
        TableEditorPopUp.add(DuplicateBtn);

        RemoveBtn.setText(TXTBundle.getString("Remove"));
        RemoveBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RemoveBtnActionPerformed(evt);
            }
        });
        TableEditorPopUp.add(RemoveBtn);

        setLayout(new java.awt.BorderLayout());

        PanelOptionsIN.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.RIGHT));

        VarLabel.setText(varLabelString+ ":");
        PanelOptionsIN.add(VarLabel);

        AddRow.setText(TXTBundle.getString("NewVar"));
        AddRow.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddRowActionPerformed(evt);
            }
        });
        PanelOptionsIN.add(AddRow);

        DeleteRow.setText(TXTBundle.getString("DelVar"));
        DeleteRow.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DeleteRowActionPerformed(evt);
            }
        });
        PanelOptionsIN.add(DeleteRow);

        add(PanelOptionsIN, java.awt.BorderLayout.NORTH);

        TableScrollPane.setAutoscrolls(true);
        TableScrollPane.setViewportView(VarTable);

        VarTable.setComponentPopupMenu(TableEditorPopUp);
        VarTable.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        VarTable.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        VarTable.setShowGrid(true);
        VarTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                VarTableMouseClicked(evt);
            }
        });
        VarTable.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                VarTableKeyPressed(evt);
            }
        });
        TableScrollPane.setViewportView(VarTable);

        add(TableScrollPane, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents

    /**
     * Actions permitted on the table: - if DELETE is pressed and a row is
     * selected delete the row - if ESCAPE then clear selection - if ENTER
     * create new variable if these conditions are met: - Last row selected:
     * duplicate last row and append it to the end - No row is selected: add a
     * blank default Variable to the end
     *
     * @param evt
     */
    private void VarTableKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_VarTableKeyPressed
        //Get selected index
        int selectedIndex = VarTable.getSelectedRow();
        //Deletion check
        if (evt.getKeyCode() == KeyEvent.VK_DELETE && selectedIndex > -1) {
            /*
            delete the row and consume the event to avoid error sound from 
            key pressed by the system
             */
            vtr.removeRow(selectedIndex);
            evt.consume();
        } else if (evt.getKeyCode() == KeyEvent.VK_ESCAPE) {
            /*
            clear the selection and consume the event to avoid error sound from 
            key pressed by the system
             */
            VarTable.getSelectionModel().clearSelection();
            evt.consume();
        } else if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            boolean shouldAdd = shouldAddVar();
            if (!shouldAdd) {
                return;
            }
            //Enter has been pressed: check if last row or no row is selected
            if (selectedIndex == -1 || selectedIndex >= vtr.getRowCount()) {
                //no rows selected: add default blank var
                vtr.addRow(new Variable("", VariableType.Bool));
            } else if (selectedIndex == (vtr.getRowCount() - 1)) {
                //Selected the last row: duplicate the variable and add it
                Variable row = vtr.getRow(selectedIndex);
                Variable v = new Variable(TextToolHandler.getNextName(row.getName()), row.getType());
                v.getModifier().of(row);
                v.setDefaultValue(row.getDefaultValue());
                v.setComment(row.getComment());
                vtr.addRow(v);
            }
        }
    }//GEN-LAST:event_VarTableKeyPressed

    private void DeleteRowActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DeleteRowActionPerformed
        //Delete Variable if valid index
        deleteCurrent();
    }//GEN-LAST:event_DeleteRowActionPerformed

    private void AddRowActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddRowActionPerformed
        boolean shouldAdd = shouldAddVar();
        if (!shouldAdd) {
            return;
        }
        //Append new blank variable
        vtr.addRow(new Variable("", VariableType.Bool));
    }//GEN-LAST:event_AddRowActionPerformed

    private void MoveUpBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MoveUpBtnActionPerformed
        //Move the current selected row closer to the first
        moveCurrent(VariableTableRender.Direction.UP);
    }//GEN-LAST:event_MoveUpBtnActionPerformed

    private void MoveDownBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MoveDownBtnActionPerformed
        //Move the current selected row closer to the be the last row
        moveCurrent(VariableTableRender.Direction.DOWN);
    }//GEN-LAST:event_MoveDownBtnActionPerformed

    private void DuplicateBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DuplicateBtnActionPerformed
        // Duplicate current row if selected and append it as the next
        duplicateCurrent();
    }//GEN-LAST:event_DuplicateBtnActionPerformed

    private void RemoveBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RemoveBtnActionPerformed
        deleteCurrent();
    }//GEN-LAST:event_RemoveBtnActionPerformed

    private void VarTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_VarTableMouseClicked
        if (evt.getButton() == MouseEvent.BUTTON3) {
            showPopup(evt.getX(), evt.getY());
        }
    }//GEN-LAST:event_VarTableMouseClicked

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AddRow;
    private javax.swing.JButton DeleteRow;
    private javax.swing.JMenuItem DuplicateBtn;
    private javax.swing.JMenuItem MoveDownBtn;
    private javax.swing.JMenuItem MoveUpBtn;
    private javax.swing.JPanel PanelOptionsIN;
    private javax.swing.JPopupMenu.Separator PopUpSep;
    private javax.swing.JMenuItem RemoveBtn;
    private javax.swing.JPopupMenu TableEditorPopUp;
    private javax.swing.JScrollPane TableScrollPane;
    private javax.swing.JLabel VarLabel;
    private javax.swing.JTable VarTable;
    // End of variables declaration//GEN-END:variables

    private void initVariableTableModel() {
        vtr = new VariableTableRender(new TableRow<Variable>() {
            @Override
            public Object getValueAt(CustomTableColumn col, Variable rowValue) {
                //If this handler is called then a non-default column is being selected
                switch (col.getColumnName()) {
                    default -> {
                        return null;
                    }
                }
            }

            @Override
            public void setValueAt(CustomTableColumn col, Object value, Variable rowReference) {
                //All default columns are already handled
            }

            @Override
            public boolean isEditable(CustomTableColumn col, Variable rowReference) {
                //Every cell should be editable in this context
                return true;
            }
        }, vars);

        vtr.setTypeListener((var, varType) -> {
            //Listen for any table cell modification
            if (null == varType) {
                var.setType(VariableType.Bool);
                var.getModifier().reset();
            } else {
                //handle string and arrays as they need an additional dialog
                switch (varType) {
                    case String, WString -> {
                        var.setType(varType);
                        var.getModifier().setIsList(true, 5);
                        showStringDialog(var);
                    }
                    case Array -> {
                        var.setType(VariableType.Bool);
                        var.getModifier().setIsArray(true, 0, 10);
                        showArrayDialog(var);
                    }
                    default -> {
                        var.setType(varType);
                        var.getModifier().reset();
                    }
                }
            }
        });

        VarTable.setModel(vtr);
        VarTable.getModel().addTableModelListener((TableModelEvent e) -> {
            //Select last row when a new row is added
            if (e.getType() == TableModelEvent.INSERT) {
                int row = vtr.getRowCount() - 1;
                VarTable.editCellAt(row, 0);
                VarTable.getSelectionModel().setSelectionInterval(row, row);
            }
        });
        VarTable.addComponentListener(new ComponentListener() {
            @Override
            public void componentResized(ComponentEvent e) {
                //Scroll down to the last element
                TableScrollPane.scrollRectToVisible(VarTable.getCellRect(VarTable.getRowCount() - 1, 0, true));
            }

            @Override
            public void componentMoved(ComponentEvent e) {
            }

            @Override
            public void componentShown(ComponentEvent e) {
            }

            @Override
            public void componentHidden(ComponentEvent e) {
            }
        });

        /**
         * Add cell editors for the columns: "name", "type", "start value",
         * "comment". If this table is opened to edit FB or FC instance then
         * only the start value should be editable
         */
        if (contentEditable) {
            VarTable.getColumnModel().getColumn(3).setCellEditor(vtr.getColumn(3).getCellEditor());
            VarTable.getColumnModel().getColumn(0).setCellEditor(vtr.getColumn(0).getCellEditor());
            VarTable.getColumnModel().getColumn(1).setCellEditor(vtr.getColumn(1).getCellEditor());
        }
        VarTable.getColumnModel().getColumn(2).setCellEditor(vtr.getColumn(2).getCellEditor());

        TableEditorPopUp.pack();

        //The buttons should be enaled only for editing resources not linked to
        //any other resources
        AddRow.setEnabled(contentEditable);
        DeleteRow.setEnabled(contentEditable);
        DuplicateBtn.setEnabled(contentEditable);
        MoveDownBtn.setEnabled(contentEditable);
        MoveUpBtn.setEnabled(contentEditable);
    }

    public List<Variable> getVariables() {
        return vtr.getVariables();
    }

    /**
     * Duplicate current row if one is selected: this action adds a new variable
     * to the resource coping the selected variable
     */
    private void duplicateCurrent() {
        int selectedIndex = VarTable.getSelectedRow();
        if (selectedIndex > 0 && selectedIndex < vtr.getRowCount()) {//>0 la prima non la posso muovere
            Variable row = vtr.getRow(selectedIndex);
            if (row != null) {
                Variable v = new Variable(TextToolHandler.getNextName(row.getName()), row.getType());
                v.getModifier().of(row);
                v.setDefaultValue(row.getDefaultValue());
                v.setComment(row.getComment());
                vtr.addRow(selectedIndex + 1, v);
            }
        }
    }

    private void deleteCurrent() {
        int selectedIndex = VarTable.getSelectedRow();
        if (selectedIndex != -1 && selectedIndex < vtr.getRowCount()) {
            vtr.removeRow(selectedIndex);
        }
    }

    private void moveCurrent(VariableTableRender.Direction direction) {
        int selectedIndex = VarTable.getSelectedRow();
        if (selectedIndex > 0 && selectedIndex < vtr.getRowCount()) {//>0 la prima non la posso muovere
            Variable row = vtr.getRow(selectedIndex);
            if (row != null) {
                vtr.moveRow(row, direction);
            }
        }
    }

    private void showPopup(int x, int y) {
        int rowAtPoint = VarTable.rowAtPoint(new Point(x, y));
        if (rowAtPoint > -1) {
            VarTable.getSelectionModel().setSelectionInterval(rowAtPoint, rowAtPoint);
            TableEditorPopUp.show(VarTable, x, y);
            TableEditorPopUp.setVisible(true);
        }
    }

    private boolean shouldAddVar() {
        Variable lastVar = vtr.getLastRow();
        if (lastVar == null) {
            return true;
        }
        return !lastVar.getName().isBlank();
    }

    private Point getSelectionRowPoint() {
        if (VarTable.getSelectionModel().isSelectionEmpty()) {
            return null;
        }
        Rectangle cellRect = VarTable.getCellRect(VarTable.getSelectedRow(), 1, true);
        Point p = cellRect.getLocation();
        p.translate(0, cellRect.y);
        return p;
    }

    private void showArrayDialog(Variable v) {
        showDialog(v, true);
    }

    private void showStringDialog(Variable v) {
        showDialog(v, false);
    }

    private void showDialog(Variable v, boolean array) {
        JDialog dialog = new JDialog();
        ClosableFrame cf;
        if (array) {
            ArrayVariableDefinition cvd = new ArrayVariableDefinition(v);
            dialog.add(cvd);
            cf = cvd;
        } else {
            StringVariableDefinition svd = new StringVariableDefinition(v);
            dialog.add(svd);
            cf = svd;
        }
        cf.addCloseRequestListener(() -> {
            dialog.setVisible(false);
            dialog.dispose();
        });
        dialog.setUndecorated(true);
        dialog.pack();
        Point position = getSelectionRowPoint();
        if (position != null) {
            Point p = VarTable.getLocationOnScreen();
            p.translate(position.x, position.y);
            dialog.setLocation(p);
        }
        dialog.setModalityType(Dialog.ModalityType.APPLICATION_MODAL);
        dialog.setAlwaysOnTop(true);
        dialog.setVisible(true);
    }
}
