/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package net.vnleng.generator.gui.panels.settings;

import java.util.Arrays;
import java.util.Locale;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import net.vnleng.generator.commons.events.CloseRequestListener;
import net.vnleng.generator.resources.TextResources;
import net.vnleng.generator.settings.DataInitializer;

/**
 *
 * @author gabri
 */
public class SettingsPane extends javax.swing.JPanel {

    private CloseRequestListener listener;

    /**
     * Creates new form SettingsPane
     */
    public SettingsPane() {
        initComponents();
        init();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        LanguageLabel = new javax.swing.JLabel();
        LanguagesCB = new javax.swing.JComboBox<>();
        ButtonsPanel = new javax.swing.JPanel();
        UndoBtn = new javax.swing.JButton();
        SaveBtn = new javax.swing.JButton();

        setLayout(new java.awt.GridLayout(2, 0));

        jPanel1.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT));

        LanguageLabel.setText(TextResources.GUITextBundle.getString("Language")+":");
        jPanel1.add(LanguageLabel);

        LanguagesCB.setModel(new javax.swing.DefaultComboBoxModel<>(Locale.getAvailableLocales()));
        jPanel1.add(LanguagesCB);

        add(jPanel1);

        ButtonsPanel.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.RIGHT));

        UndoBtn.setText(TextResources.GUITextBundle.getString("Undo"));
        UndoBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UndoBtnActionPerformed(evt);
            }
        });
        ButtonsPanel.add(UndoBtn);

        SaveBtn.setText(TextResources.GUITextBundle.getString("Save"));
        SaveBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SaveBtnActionPerformed(evt);
            }
        });
        ButtonsPanel.add(SaveBtn);

        add(ButtonsPanel);
    }// </editor-fold>//GEN-END:initComponents

    private void UndoBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UndoBtnActionPerformed
        // TODO add your handling code here:
        if (listener != null) {
            listener.onCloseRequest();
        }
    }//GEN-LAST:event_UndoBtnActionPerformed

    private void SaveBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SaveBtnActionPerformed
        // TODO add your handling code here:
        Locale selectedItem = (Locale) LanguagesCB.getSelectedItem();
        if (selectedItem != null) {
            DataInitializer.getInstance().setLocale(selectedItem);
            JOptionPane.showMessageDialog(this, TextResources.GUITextBundle.getString("ReloadToApply"), TextResources.GUITextBundle.getString("Settings"), JOptionPane.OK_OPTION);
        }
        if (listener != null) {
            listener.onCloseRequest();
        }
    }//GEN-LAST:event_SaveBtnActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel ButtonsPanel;
    private javax.swing.JLabel LanguageLabel;
    private javax.swing.JComboBox<Locale> LanguagesCB;
    private javax.swing.JButton SaveBtn;
    private javax.swing.JButton UndoBtn;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables

    private void init() {
        Locale[] availableLocales = new Locale[]{Locale.ITALIAN,Locale.ENGLISH};
        Arrays.sort(availableLocales, (o1, o2) -> {
            return o1.toString().compareTo(o2.toString());
        });
        LanguagesCB.setModel(new DefaultComboBoxModel<>(availableLocales));
        Locale current = DataInitializer.getInstance().getLocale();
        LanguagesCB.setSelectedItem(current);
    }

    public void addCloseRequestListener(CloseRequestListener crl) {
        listener = crl;
    }

}
