package net.vnleng.generator.gui;

import net.vnleng.generator.data.shared.SharedData;
import com.formdev.flatlaf.FlatDarkLaf;
import java.io.File;
import java.io.FileNotFoundException;
import java.io.IOException;
import java.util.ResourceBundle;
import javax.swing.JFileChooser;
import net.vnleng.generator.gui.panels.project.OpenProjectPane;
import javax.swing.JInternalFrame;
import javax.swing.JOptionPane;
import javax.swing.UIManager;
import javax.swing.filechooser.FileFilter;
import net.vnleng.generator.commons.events.CallbackEventHandler;
import net.vnleng.generator.commons.events.EventHandler;
import net.vnleng.generator.data.Project;
import net.vnleng.generator.data.ints.res.ResourceElement;
import net.vnleng.generator.data.ints.res.ResourceType;
import net.vnleng.generator.data.scl.impls.DataBlockElement;
import net.vnleng.generator.data.scl.impls.DataBlockInstanceElement;
import net.vnleng.generator.data.scl.impls.FunctionBlockElement;
import net.vnleng.generator.data.scl.impls.FunctionElement;
import net.vnleng.generator.data.scl.ints.FunctionResource;
import net.vnleng.generator.data.serialization.ProjectSerializer;
import net.vnleng.generator.data.serialization.ProjectUnrecognizedError;
import net.vnleng.generator.data.serialization.ProjectVersionError;
import net.vnleng.generator.gui.panels.FrameCreator;
import net.vnleng.generator.gui.panels.content.FunctionDefinitionPanel;
import net.vnleng.generator.gui.panels.project.ProjectContentPane;
import net.vnleng.generator.gui.panels.settings.SettingsPane;
import net.vnleng.generator.resources.ProjectResourceHandler;
import net.vnleng.generator.resources.TextResources;

/**
 *
 * @author gabri
 */
public class EntryMainApp extends javax.swing.JFrame {

    private static final SharedData sharedData = new SharedData();
    private final ResourceBundle TXTbundle;
    private final ResourceBundle DIAGbundle;

    /**
     * Creates new form MainApp
     */
    public EntryMainApp() {
        TXTbundle = TextResources.GUITextBundle;
        DIAGbundle = TextResources.DialogsTextBundle;
        initComponents();
        enableActions(false);
        initDataListeners();
        setupFrontPage();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        DesktopPane = new javax.swing.JDesktopPane();
        AppMenuBar = new javax.swing.JMenuBar();
        FileMenu = new javax.swing.JMenu();
        NewProject = new javax.swing.JMenuItem();
        OpenProject = new javax.swing.JMenuItem();
        Sep1 = new javax.swing.JPopupMenu.Separator();
        SaveProject = new javax.swing.JMenuItem();
        SaveAsProject = new javax.swing.JMenuItem();
        CloseProject = new javax.swing.JMenuItem();
        Sep2 = new javax.swing.JPopupMenu.Separator();
        ExitProgram = new javax.swing.JMenuItem();
        EditMenu = new javax.swing.JMenu();
        ResourceDefinitionItem = new javax.swing.JMenuItem();
        Sep3 = new javax.swing.JPopupMenu.Separator();
        Settings = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(755, 441));
        setName("MainFrame"); // NOI18N
        setSize(new java.awt.Dimension(840, 620));
        getContentPane().setLayout(new java.awt.GridLayout(1, 0));

        DesktopPane.setAutoscrolls(true);
        DesktopPane.setMinimumSize(new java.awt.Dimension(755, 418));
        getContentPane().add(DesktopPane);

        FileMenu.setText("File");

        NewProject.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_N, java.awt.event.InputEvent.SHIFT_DOWN_MASK | java.awt.event.InputEvent.CTRL_DOWN_MASK));
        NewProject.setText(TextResources.GUITextBundle.getString("NewProject"));
        NewProject.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NewProjectActionPerformed(evt);
            }
        });
        FileMenu.add(NewProject);

        OpenProject.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_O, java.awt.event.InputEvent.SHIFT_DOWN_MASK | java.awt.event.InputEvent.CTRL_DOWN_MASK));
        OpenProject.setText(TextResources.GUITextBundle.getString("OpenProject"));
        OpenProject.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                OpenProjectActionPerformed(evt);
            }
        });
        FileMenu.add(OpenProject);
        FileMenu.add(Sep1);

        SaveProject.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_S, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        SaveProject.setText(TextResources.GUITextBundle.getString("Save"));
        SaveProject.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SaveProjectActionPerformed(evt);
            }
        });
        FileMenu.add(SaveProject);

        SaveAsProject.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_S, java.awt.event.InputEvent.SHIFT_DOWN_MASK | java.awt.event.InputEvent.CTRL_DOWN_MASK));
        SaveAsProject.setText(TextResources.GUITextBundle.getString("SaveAs"));
        SaveAsProject.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SaveAsProjectActionPerformed(evt);
            }
        });
        FileMenu.add(SaveAsProject);

        CloseProject.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_W, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        CloseProject.setText(TextResources.GUITextBundle.getString("CloseProject"));
        CloseProject.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CloseProjectActionPerformed(evt);
            }
        });
        FileMenu.add(CloseProject);
        FileMenu.add(Sep2);

        ExitProgram.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_Q, java.awt.event.InputEvent.SHIFT_DOWN_MASK | java.awt.event.InputEvent.CTRL_DOWN_MASK));
        ExitProgram.setText(TextResources.GUITextBundle.getString("Exit"));
        ExitProgram.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ExitProgramActionPerformed(evt);
            }
        });
        FileMenu.add(ExitProgram);

        AppMenuBar.add(FileMenu);

        EditMenu.setText("Edit");

        ResourceDefinitionItem.setText("Resource Def");
        ResourceDefinitionItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ResourceDefinitionItemActionPerformed(evt);
            }
        });
        EditMenu.add(ResourceDefinitionItem);
        EditMenu.add(Sep3);

        Settings.setText(TextResources.GUITextBundle.getString("Settings"));
        Settings.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SettingsActionPerformed(evt);
            }
        });
        EditMenu.add(Settings);

        AppMenuBar.add(EditMenu);

        setJMenuBar(AppMenuBar);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void NewProjectActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NewProjectActionPerformed
        // TODO add your handling code here:
        if (sharedData.getProject() == null) {
            showOpenProjectPane();
        } else {
            int showCloseAndSave = showCloseAndSave();
            if (showCloseAndSave == 1) {
                saveProject(false);
            } else if (showCloseAndSave == 0) {
                return;
            }
            sharedData.close();
        }
    }//GEN-LAST:event_NewProjectActionPerformed

    private void OpenProjectActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_OpenProjectActionPerformed
        // TODO add your handling code here:
        JFileChooser jfc = new JFileChooser();
        jfc.setAcceptAllFileFilterUsed(true);
        FileFilter ff = new FileFilter() {
            @Override
            public boolean accept(File f) {
                return f.isDirectory() || f.getName().endsWith(".gtpj");
            }

            @Override
            public String getDescription() {
                return TXTbundle.getString("FileChooserDescription");
            }
        };
        jfc.setFileFilter(ff);
        jfc.showOpenDialog(this);
        File selectedFile = jfc.getSelectedFile();
        if (selectedFile != null) {
            String path = selectedFile.getAbsolutePath();
            try {
                Project p = ProjectSerializer.deserializeProject(path);
                sharedData.setOpenedProject(p, true, path);
            } catch (FileNotFoundException ex) {
                JOptionPane.showConfirmDialog(this.getParent(), DIAGbundle.getString("FileNotFound_Message"),
                        DIAGbundle.getString("FileNotFound_Title"), JOptionPane.CLOSED_OPTION, JOptionPane.ERROR_MESSAGE);
            } catch (IOException ex) {
                JOptionPane.showConfirmDialog(this.getParent(), DIAGbundle.getString("FileNotReadable_Message"),
                        DIAGbundle.getString("FileNotReadable_Title"), JOptionPane.CLOSED_OPTION, JOptionPane.ERROR_MESSAGE);
            } catch (ProjectUnrecognizedError pue) {
                JOptionPane.showConfirmDialog(this.getParent(), DIAGbundle.getString("ProjectNotRecognyzed_Message"),
                        DIAGbundle.getString("ProjectNotRecognyzed_Title"), JOptionPane.CLOSED_OPTION, JOptionPane.WARNING_MESSAGE);
            } catch (ProjectVersionError pve) {
                JOptionPane.showConfirmDialog(this.getParent(), DIAGbundle.getString("ProjectIncompatible_Message"),
                        DIAGbundle.getString("ProjectIncompatible_Title"), JOptionPane.CLOSED_OPTION, JOptionPane.WARNING_MESSAGE);
            }
        }
    }//GEN-LAST:event_OpenProjectActionPerformed

    private void ExitProgramActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ExitProgramActionPerformed
        // TODO add your handling code here:
        if (sharedData.hasBeenEdited()) {
            int showOptionDialog = showCloseAndSave();
            if (showOptionDialog == 1) {
                saveProject(false);
                System.exit(0);
            } else if (showOptionDialog == 2) {
                System.exit(0);
            }
        } else {
            System.exit(0);
        }

    }//GEN-LAST:event_ExitProgramActionPerformed

    private void SaveProjectActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SaveProjectActionPerformed
        // TODO add your handling code here:
        saveProject(false);
    }//GEN-LAST:event_SaveProjectActionPerformed

    private void SaveAsProjectActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SaveAsProjectActionPerformed
        // TODO add your handling code here:
        saveProject(true);
    }//GEN-LAST:event_SaveAsProjectActionPerformed

    private void CloseProjectActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CloseProjectActionPerformed
        // TODO add your handling code here:
        if (sharedData.hasBeenEdited()) {
            int showOptionDialog = showCloseAndSave();
            if (showOptionDialog == 1) {
                saveProject(false);
                sharedData.close();
            } else if (showOptionDialog == 2) {
                sharedData.close();
            }
        } else {
            sharedData.close();
        }
    }//GEN-LAST:event_CloseProjectActionPerformed

    private void SettingsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SettingsActionPerformed
        // TODO add your handling code here:
        SettingsPane sp = new SettingsPane();
        JInternalFrame frame = FrameCreator.createFrame(TXTbundle.getString("Settings"), false, sp);
        sp.addCloseRequestListener(() -> {
            frame.setVisible(false);
            this.DesktopPane.remove(frame);
        });
        frame.setLayer(4);
        frame.setMaximizable(false);
        this.DesktopPane.add(frame);
    }//GEN-LAST:event_SettingsActionPerformed

    private void ResourceDefinitionItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ResourceDefinitionItemActionPerformed
        // TODO add your handling code here:
        if (sharedData != null && sharedData.getProject() != null) {
//            JInternalFrame jif = FrameCreator.createFrame("prova", true, new FunctionDefinitionPanel(sharedData, ResourceType.FunctionBlock, null));
//            DesktopPane.add(jif);
        }
    }//GEN-LAST:event_ResourceDefinitionItemActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            UIManager.setLookAndFeel(new FlatDarkLaf());
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            System.err.println(ex.toString());
        }
        //</editor-fold>
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            EntryMainApp app = new EntryMainApp();
            app.setIconImage(ProjectResourceHandler.AppIcon_512.getImage());
            app.pack();
            app.setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuBar AppMenuBar;
    private javax.swing.JMenuItem CloseProject;
    private javax.swing.JDesktopPane DesktopPane;
    private javax.swing.JMenu EditMenu;
    private javax.swing.JMenuItem ExitProgram;
    private javax.swing.JMenu FileMenu;
    private javax.swing.JMenuItem NewProject;
    private javax.swing.JMenuItem OpenProject;
    private javax.swing.JMenuItem ResourceDefinitionItem;
    private javax.swing.JMenuItem SaveAsProject;
    private javax.swing.JMenuItem SaveProject;
    private javax.swing.JPopupMenu.Separator Sep1;
    private javax.swing.JPopupMenu.Separator Sep2;
    private javax.swing.JPopupMenu.Separator Sep3;
    private javax.swing.JMenuItem Settings;
    // End of variables declaration//GEN-END:variables

    private int showCloseAndSave() {
        String options[] = new String[]{TXTbundle.getString("Undo"),
            TXTbundle.getString("SaveAndClose"),
            TXTbundle.getString("Close")
        };
        return JOptionPane.showOptionDialog(this, "Hai modifiche non salvate.\nVuoi uscire senza salvare?", "Salva Progetto?",
                0, JOptionPane.INFORMATION_MESSAGE, null, options, options[1]);
    }

    private void initDataListeners() {
        sharedData.addProjectOpenedEventListener((data) -> {
            if (sharedData.hasBeenEdited()) {

                this.setTitle(data.getProjectName() + "*");
            } else {
                this.setTitle(data.getProjectName());
            }
            if (data.getResources().isEmpty()) {
                data.addResource(new FunctionBlockElement("Test"));
                data.addResource(new FunctionElement("Test2"));
                data.addResource(new FunctionElement("Test3"));
                data.addResource(new FunctionElement("Test4"));
                data.addResource(new DataBlockElement("Test5"));
                data.addResource(new DataBlockInstanceElement("Test5", (FunctionResource) data.getResource(ResourceType.Function, "Test4")));
            }
            showProjectContentPane();
            enableActions(true);
        });
        sharedData.addSaveEventListener((data) -> {
            if (data.hasBeenEdited()) {
                this.setTitle(data.getProject().getProjectName() + "*");
            } else {
                this.setTitle(data.getProject().getProjectName());
            }
        });
        sharedData.addProjectClosedEventListener((data) -> {
            this.setTitle("");
            this.DesktopPane.removeAll();
            this.DesktopPane.repaint();
            this.setupFrontPage();
            enableActions(false);
        });
    }

    private void enableActions(boolean enable) {
        this.SaveAsProject.setEnabled(enable);
        this.SaveProject.setEnabled(enable);
        this.CloseProject.setEnabled(enable);
    }

    private JInternalFrame showOpenProjectPane() {
        OpenProjectPane content = new OpenProjectPane(sharedData);
        JInternalFrame jif = FrameCreator.createFrame(TXTbundle.getString("NewProject"), false, content);
        jif.setMaximizable(false);
        jif.setLayer(3);
        this.DesktopPane.add(jif);
        content.focus();

        content.addCloseRequestListener(() -> {
            jif.setVisible(false);
            this.DesktopPane.remove(jif);
        });
        return jif;
    }

    private JInternalFrame showProjectContentPane() {
        EventHandler<ResourceType, ResourceElement, CallbackEventHandler<ResourceElement>> eh = new EventHandler<>();
        eh.addHandler(ResourceType.Function, (element) -> {
            FunctionElement functionElement;
            if (element != null) {
                functionElement = (FunctionElement) element;
            } else {
                String name = askResourceName();
                if (name == null || name.isEmpty()) {
                    return;
                }
                functionElement = new FunctionElement(name);
            }
            JInternalFrame jif = FrameCreator.createFrame(functionElement.getName() + "[FC]", true, new FunctionDefinitionPanel(sharedData, functionElement), DesktopPane);
            jif.setLayer(1);
        });
        eh.addHandler(ResourceType.FunctionBlock, (element) -> {
            FunctionBlockElement functionElement;
            if (element != null) {
                functionElement = (FunctionBlockElement) element;
            } else {
                String name = askResourceName();
                if (name == null || name.isEmpty()) {
                    return;
                }
                functionElement = new FunctionBlockElement(name);
            }
            JInternalFrame jif = FrameCreator.createFrame(functionElement.getName() + "[FB]", true, new FunctionDefinitionPanel(sharedData, functionElement), DesktopPane);
            jif.setLayer(1);
        });
        eh.addHandler(ResourceType.DataBlock, (element) -> {
            DataBlockElement dbElement;
            if (element != null) {
                dbElement = (DataBlockElement) element;
            } else {
                String name = askResourceName();
                if (name == null || name.isEmpty()) {
                    return;
                }
                dbElement = new DataBlockElement(name);
            }
            JInternalFrame jif = FrameCreator.createFrame(dbElement.getName() + "[DB]", true, new FunctionDefinitionPanel(sharedData, dbElement), DesktopPane);
            jif.setLayer(1);
        });
        ProjectContentPane content = new ProjectContentPane(sharedData, eh);
        JInternalFrame jif = FrameCreator.createFrame(TXTbundle.getString("ProjectStructure_short"), true, content);
        jif.setLayer(1);
        this.DesktopPane.add(jif);
        return jif;
    }

    private String askResourceName() {
        return JOptionPane.showInputDialog(DIAGbundle.getString("RequestInputName"));
    }

    private void setupFrontPage() {
        JInternalFrame frame = showOpenProjectPane();
        int xpos = (DesktopPane.getWidth() - frame.getWidth()) / 2;
        int ypos = (DesktopPane.getHeight() - frame.getHeight()) / 2;
        frame.setLocation(xpos, ypos);
    }

    private void saveProject(boolean saveAs) {
        String filePath = null;
        if (sharedData.hasFileAssocieted() && !saveAs) {
            filePath = sharedData.getFilePath();
        } else {
            JFileChooser jfc = new JFileChooser();
            jfc.setFileFilter(new FileFilter() {
                @Override
                public boolean accept(File f) {
                    return f.isDirectory() || f.getName().toLowerCase().endsWith(".gtpj");
                }

                @Override
                public String getDescription() {
                    return TXTbundle.getString("FileChooserDescription");
                }
            });
            int showSaveDialog = jfc.showSaveDialog(this);
            if (showSaveDialog == JFileChooser.CANCEL_OPTION || showSaveDialog == JFileChooser.ERROR_OPTION) {
                return;
            } else if (showSaveDialog == JFileChooser.APPROVE_OPTION) {
                File selectedFile = jfc.getSelectedFile();
                filePath = selectedFile.toString();
                if (selectedFile.isDirectory()) {
                    filePath = filePath + File.separatorChar + sharedData.getProject().getProjectName() + ".gtpj";
                } else if (!selectedFile.getName().endsWith(".gtpj")) {
                    filePath = filePath + ".gtpj";
                }
            }
        }
        try {
            sharedData.save(filePath);
        } catch (IOException ex) {
            System.getLogger(EntryMainApp.class.getName()).log(System.Logger.Level.ERROR, (String) null, ex);
        }
    }

}
