/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package net.vnleng.generator.gui.panels.project;

import java.awt.event.KeyEvent;
import net.vnleng.generator.commons.events.CloseRequestListener;
import net.vnleng.generator.data.Project;
import net.vnleng.generator.data.shared.SharedData;
import java.io.File;
import java.io.FileNotFoundException;
import java.io.IOException;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.filechooser.FileFilter;
import net.vnleng.generator.data.serialization.ProjectSerializer;
import net.vnleng.generator.data.serialization.ProjectUnrecognizedError;
import net.vnleng.generator.data.serialization.ProjectVersionError;

/**
 *
 * @author gabri
 */
public class OpenProjectPane extends javax.swing.JPanel {

    private final SharedData sharedData;
    private CloseRequestListener listener;

    /**
     * Creates new form ProjectCreator
     *
     * @param sharedData
     */
    public OpenProjectPane(SharedData sharedData) {
        initComponents();
        this.sharedData = sharedData;
        this.ProjectNameTF.requestFocusInWindow();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Title = new javax.swing.JLabel();
        NewProjectPanel = new javax.swing.JPanel();
        NewLabel = new javax.swing.JLabel();
        ProjectNameTF = new javax.swing.JTextField();
        GenerateProject = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        Title1 = new javax.swing.JLabel();
        NewProjectPanel1 = new javax.swing.JPanel();
        OpenLabel = new javax.swing.JLabel();
        ProjectPathTF = new javax.swing.JTextField();
        OpenProject = new javax.swing.JButton();
        ShowExplorer = new javax.swing.JButton();

        setMaximumSize(new java.awt.Dimension(330, 209));
        setMinimumSize(new java.awt.Dimension(330, 209));

        Title.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        Title.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Title.setText("Nuovo Progetto");

        NewLabel.setText("Nome:");

        ProjectNameTF.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                ProjectNameTFKeyPressed(evt);
            }
        });

        GenerateProject.setText("Genera");
        GenerateProject.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GenerateProjectActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout NewProjectPanelLayout = new javax.swing.GroupLayout(NewProjectPanel);
        NewProjectPanel.setLayout(NewProjectPanelLayout);
        NewProjectPanelLayout.setHorizontalGroup(
            NewProjectPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(NewProjectPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(NewProjectPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(NewProjectPanelLayout.createSequentialGroup()
                        .addComponent(NewLabel)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(NewProjectPanelLayout.createSequentialGroup()
                        .addComponent(ProjectNameTF, javax.swing.GroupLayout.DEFAULT_SIZE, 234, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(GenerateProject)))
                .addContainerGap())
        );
        NewProjectPanelLayout.setVerticalGroup(
            NewProjectPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(NewProjectPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(NewLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(NewProjectPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ProjectNameTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(GenerateProject))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        Title1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        Title1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Title1.setText("Apri Progetto");

        OpenLabel.setText("Percorso Progetto:");

        OpenProject.setText("Apri");
        OpenProject.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                OpenProjectActionPerformed(evt);
            }
        });

        ShowExplorer.setText("...");
        ShowExplorer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ShowExplorerActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout NewProjectPanel1Layout = new javax.swing.GroupLayout(NewProjectPanel1);
        NewProjectPanel1.setLayout(NewProjectPanel1Layout);
        NewProjectPanel1Layout.setHorizontalGroup(
            NewProjectPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(NewProjectPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(NewProjectPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(NewProjectPanel1Layout.createSequentialGroup()
                        .addComponent(OpenLabel)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(NewProjectPanel1Layout.createSequentialGroup()
                        .addComponent(ProjectPathTF, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(ShowExplorer, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(OpenProject)))
                .addContainerGap())
        );
        NewProjectPanel1Layout.setVerticalGroup(
            NewProjectPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(NewProjectPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(OpenLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(NewProjectPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ProjectPathTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ShowExplorer)
                    .addComponent(OpenProject))
                .addContainerGap(10, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Title)
                    .addComponent(NewProjectPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 324, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Title1)
                    .addComponent(NewProjectPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(Title)
                .addGap(6, 6, 6)
                .addComponent(NewProjectPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(6, 6, 6)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(6, 6, 6)
                .addComponent(Title1)
                .addGap(6, 6, 6)
                .addComponent(NewProjectPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void GenerateProjectActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GenerateProjectActionPerformed
        // TODO add your handling code here:
        String text = ProjectNameTF.getText();
        if ("".equals(text.trim())) {
            return;
        }
        Project p = new Project(text);
        sharedData.setOpenedProject(p, false, null);
        if (this.listener != null) {
            listener.onCloseRequest();
        }
    }//GEN-LAST:event_GenerateProjectActionPerformed

    private void OpenProjectActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_OpenProjectActionPerformed
        // TODO add your handling code here:
        String text = ProjectPathTF.getText();
        if ("".equals(text.trim())) {
            return;
        }
        openProject(text);
    }//GEN-LAST:event_OpenProjectActionPerformed

    private void ShowExplorerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ShowExplorerActionPerformed
        // TODO add your handling code here:
        JFileChooser jfc = new JFileChooser();
        jfc.setAcceptAllFileFilterUsed(true);
        FileFilter ff = new FileFilter() {
            @Override
            public boolean accept(File f) {
                return f.isDirectory() || f.getName().endsWith(".gtpj");
            }

            @Override
            public String getDescription() {
                return "GTPJ - File di Progetto";
            }
        };
        jfc.setFileFilter(ff);
        jfc.showOpenDialog(this);
        File selectedFile = jfc.getSelectedFile();
        if (selectedFile != null) {
            ProjectPathTF.setText(selectedFile.getAbsolutePath());
            openProject(ProjectPathTF.getText());
        }
    }//GEN-LAST:event_ShowExplorerActionPerformed

    private void ProjectNameTFKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_ProjectNameTFKeyPressed
        // TODO add your handling code here:
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            this.GenerateProjectActionPerformed(null);
        }
    }//GEN-LAST:event_ProjectNameTFKeyPressed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton GenerateProject;
    private javax.swing.JLabel NewLabel;
    private javax.swing.JPanel NewProjectPanel;
    private javax.swing.JPanel NewProjectPanel1;
    private javax.swing.JLabel OpenLabel;
    private javax.swing.JButton OpenProject;
    private javax.swing.JTextField ProjectNameTF;
    private javax.swing.JTextField ProjectPathTF;
    private javax.swing.JButton ShowExplorer;
    private javax.swing.JLabel Title;
    private javax.swing.JLabel Title1;
    private javax.swing.JSeparator jSeparator1;
    // End of variables declaration//GEN-END:variables

    public void addCloseRequestListener(CloseRequestListener crl) {
        listener = crl;
    }

    public void focus() {
        this.ProjectNameTF.requestFocusInWindow();
    }

    private void openProject(String path) {
        try {
            Project p = ProjectSerializer.deserializeProject(path);
            sharedData.setOpenedProject(p, true, path);
            if (this.listener != null) {
                listener.onCloseRequest();
            }
        } catch (FileNotFoundException ex) {
            JOptionPane.showConfirmDialog(this.getParent(), "Non è possibile trovare il file progetto.", "File non trovato", JOptionPane.CLOSED_OPTION, JOptionPane.ERROR_MESSAGE);
        } catch (IOException ex) {
            JOptionPane.showConfirmDialog(this.getParent(), "Non è possibile leggere il file progetto.", "File non leggibile", JOptionPane.CLOSED_OPTION, JOptionPane.ERROR_MESSAGE);
        } catch (ProjectUnrecognizedError pue) {
            JOptionPane.showConfirmDialog(this.getParent(), "Il file progetto non può essere aperto\nin quanto risulta danneggiato.", "Progetto non riconosciuto", JOptionPane.CLOSED_OPTION, JOptionPane.WARNING_MESSAGE);
        } catch (ProjectVersionError pve) {
            JOptionPane.showConfirmDialog(this.getParent(), "Il file progetto non può essere aperto in quanto\nrisulta creato con una versione differente.", "Progetto Incompatibile", JOptionPane.CLOSED_OPTION, JOptionPane.WARNING_MESSAGE);

        }
    }

}
