/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package net.vnleng.generator.gui.panels.project;

import java.awt.event.KeyEvent;
import java.awt.event.MouseEvent;
import javax.swing.event.CellEditorListener;
import javax.swing.event.ChangeEvent;
import javax.swing.tree.DefaultMutableTreeNode;
import javax.swing.tree.DefaultTreeModel;
import javax.swing.tree.TreePath;
import net.vnleng.generator.commons.Pair;
import net.vnleng.generator.data.Project;
import net.vnleng.generator.data.ints.ResourceElement;
import net.vnleng.generator.data.shared.SharedData;
import net.vnleng.generator.gui.renders.ProjectTreeEditor;
import net.vnleng.generator.gui.renders.ProjectTreeRender;

/**
 *
 * @author gabri
 */
public class ProjectContentPane extends javax.swing.JPanel {

    private final SharedData sharedData;

    /**
     * Creates new form ProjectContentPane
     */
    public ProjectContentPane(SharedData data) {
        this.sharedData = data;
        initComponents();
        initDataListeners();
        initData();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        ResourceContextMenu = new javax.swing.JPopupMenu();
        RenameResource = new javax.swing.JMenuItem();
        RemoveResource = new javax.swing.JMenuItem();
        TitoloPannello = new javax.swing.JLabel();
        TabbedPane = new javax.swing.JTabbedPane();
        PagniaOggetti = new javax.swing.JPanel();
        TreeScrollPane = new javax.swing.JScrollPane();
        ProjectTree = new javax.swing.JTree();
        StructLabel = new javax.swing.JLabel();
        AddLabel = new javax.swing.JLabel();
        AddButtonsContainer = new javax.swing.JPanel();
        AddFCButton = new javax.swing.JButton();
        AddFBButton = new javax.swing.JButton();
        AddDBButton = new javax.swing.JButton();
        PaginaIstanze = new javax.swing.JPanel();

        RenameResource.setText("Rinomina");
        RenameResource.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RenameResourceActionPerformed(evt);
            }
        });
        ResourceContextMenu.add(RenameResource);

        RemoveResource.setText("Rimuovi elemento");
        RemoveResource.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RemoveResourceActionPerformed(evt);
            }
        });
        ResourceContextMenu.add(RemoveResource);

        TitoloPannello.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        TitoloPannello.setText("Contenuti del progetto");

        ProjectTree.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ProjectTreeMouseClicked(evt);
            }
        });
        ProjectTree.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                ProjectTreeKeyPressed(evt);
            }
        });
        TreeScrollPane.setViewportView(ProjectTree);

        StructLabel.setText("Struttura del progetto:");

        AddLabel.setText("Aggiungi elementi:");

        AddFCButton.setText("FC");

        AddFBButton.setText("FB");

        AddDBButton.setText("DB");

        javax.swing.GroupLayout AddButtonsContainerLayout = new javax.swing.GroupLayout(AddButtonsContainer);
        AddButtonsContainer.setLayout(AddButtonsContainerLayout);
        AddButtonsContainerLayout.setHorizontalGroup(
            AddButtonsContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(AddButtonsContainerLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(AddFCButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(AddFBButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(AddDBButton)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        AddButtonsContainerLayout.setVerticalGroup(
            AddButtonsContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(AddButtonsContainerLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(AddButtonsContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(AddFCButton)
                    .addComponent(AddFBButton)
                    .addComponent(AddDBButton))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout PagniaOggettiLayout = new javax.swing.GroupLayout(PagniaOggetti);
        PagniaOggetti.setLayout(PagniaOggettiLayout);
        PagniaOggettiLayout.setHorizontalGroup(
            PagniaOggettiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PagniaOggettiLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(PagniaOggettiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PagniaOggettiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(StructLabel)
                        .addComponent(TreeScrollPane)
                        .addComponent(AddButtonsContainer, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(AddLabel))
                .addContainerGap(317, Short.MAX_VALUE))
        );
        PagniaOggettiLayout.setVerticalGroup(
            PagniaOggettiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PagniaOggettiLayout.createSequentialGroup()
                .addGap(9, 9, 9)
                .addComponent(StructLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(TreeScrollPane, javax.swing.GroupLayout.DEFAULT_SIZE, 236, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(AddLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(AddButtonsContainer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        TabbedPane.addTab("Oggetti", PagniaOggetti);

        javax.swing.GroupLayout PaginaIstanzeLayout = new javax.swing.GroupLayout(PaginaIstanze);
        PaginaIstanze.setLayout(PaginaIstanzeLayout);
        PaginaIstanzeLayout.setHorizontalGroup(
            PaginaIstanzeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 563, Short.MAX_VALUE)
        );
        PaginaIstanzeLayout.setVerticalGroup(
            PaginaIstanzeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 336, Short.MAX_VALUE)
        );

        TabbedPane.addTab("Istanze", PaginaIstanze);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(TabbedPane)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(TitoloPannello)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(TitoloPannello)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(TabbedPane)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void ProjectTreeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ProjectTreeMouseClicked
        // TODO add your handling code here:
        if (evt.getButton() == MouseEvent.BUTTON3 && !ProjectTree.isSelectionEmpty()) {
            int x = evt.getX();
            int y = evt.getY();
            TreePath selectionPath = ProjectTree.getClosestPathForLocation(x, y);
            if (selectionPath == null) {
                selectionPath = ProjectTree.getSelectionPath();
            }
            ProjectTree.setSelectionPath(selectionPath);
            if (selectionPath == null) {
                return;
            }

            ProjectTree.getComponentPopupMenu().show(ProjectTree, x, y);
        }
    }//GEN-LAST:event_ProjectTreeMouseClicked

    private void RemoveResourceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RemoveResourceActionPerformed
        // TODO add your handling code here:
        if (!ProjectTree.isSelectionEmpty()) {
            TreePath selectionPath = ProjectTree.getSelectionPath();
            DefaultMutableTreeNode lastPathComponent = (DefaultMutableTreeNode) selectionPath.getLastPathComponent();
            Object obj = lastPathComponent.getUserObject();
            if (obj instanceof Project) {
                return;
            }
            ResourceElement re = (ResourceElement) obj;
            sharedData.removeResource(re);
        }
    }//GEN-LAST:event_RemoveResourceActionPerformed

    private void RenameResourceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RenameResourceActionPerformed
        ProjectTree.setEditable(true);
    }//GEN-LAST:event_RenameResourceActionPerformed

    private void ProjectTreeKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_ProjectTreeKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_F2) {
            ProjectTree.setEditable(true);
        }
    }//GEN-LAST:event_ProjectTreeKeyPressed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel AddButtonsContainer;
    private javax.swing.JButton AddDBButton;
    private javax.swing.JButton AddFBButton;
    private javax.swing.JButton AddFCButton;
    private javax.swing.JLabel AddLabel;
    private javax.swing.JPanel PaginaIstanze;
    private javax.swing.JPanel PagniaOggetti;
    private javax.swing.JTree ProjectTree;
    private javax.swing.JMenuItem RemoveResource;
    private javax.swing.JMenuItem RenameResource;
    private javax.swing.JPopupMenu ResourceContextMenu;
    private javax.swing.JLabel StructLabel;
    private javax.swing.JTabbedPane TabbedPane;
    private javax.swing.JLabel TitoloPannello;
    private javax.swing.JScrollPane TreeScrollPane;
    // End of variables declaration//GEN-END:variables

    private void initDataListeners() {
        ProjectTree.setComponentPopupMenu(ResourceContextMenu);
        this.sharedData.addProjectOpenedEventListener((prj) -> {
            fillProjectTree(prj);
        });
        this.sharedData.addProjectEditedEventListener((prj) -> {
            fillProjectTree(prj);
        });
        ProjectTree.setCellEditor(new ProjectTreeEditor(ProjectTree));
        ProjectTree.getCellEditor().addCellEditorListener(new CellEditorListener() {
            @Override
            public void editingStopped(ChangeEvent e) {
                Pair<ResourceElement, String> re = (Pair<ResourceElement, String>) e.getSource();
                ProjectTree.setEditable(false);
                sharedData.renameResource(re.left(), re.right());
            }

            @Override
            public void editingCanceled(ChangeEvent e) {
                ProjectTree.setEditable(false);
            }
        });
    }

    private void initData() {
        fillProjectTree(this.sharedData.getProject());
    }

    private void fillProjectTree(Project prj) {
        DefaultMutableTreeNode root;
        DefaultTreeModel treeModel;
        root = new DefaultMutableTreeNode(prj, true);
        treeModel = new DefaultTreeModel(root);
        ProjectTree.setCellRenderer(new ProjectTreeRender());
        ProjectTree.setRootVisible(true);
        prj.getResources().values().forEach(map -> {
            map.forEach((string, element) -> {
                root.add(new DefaultMutableTreeNode(element));
            });
        });
        ProjectTree.setModel(treeModel);
        ProjectTree.setShowsRootHandles(true);
    }

}
