/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package net.vnleng.generator.gui.panels.project;

import java.awt.event.KeyEvent;
import java.awt.event.MouseEvent;
import java.util.ResourceBundle;
import javax.swing.event.CellEditorListener;
import javax.swing.event.ChangeEvent;
import javax.swing.tree.DefaultMutableTreeNode;
import javax.swing.tree.DefaultTreeModel;
import javax.swing.tree.TreePath;
import net.vnleng.generator.commons.Pair;
import net.vnleng.generator.commons.events.CallbackEventHandler;
import net.vnleng.generator.commons.events.EventHandler;
import net.vnleng.generator.data.Project;
import net.vnleng.generator.data.ints.res.ResourceElement;
import net.vnleng.generator.data.ints.res.ResourceType;
import net.vnleng.generator.data.scl.impls.DataBlockElement;
import net.vnleng.generator.data.scl.impls.FunctionBlockElement;
import net.vnleng.generator.data.scl.impls.FunctionElement;
import net.vnleng.generator.data.shared.SharedData;
import net.vnleng.generator.gui.renders.tree.ProjectTreeEditor;
import net.vnleng.generator.gui.renders.tree.ProjectTreeRender;
import net.vnleng.generator.resources.TextResources;

/**
 *
 * @author gabri
 */
public class ProjectContentPane extends javax.swing.JPanel {

    private final SharedData sharedData;
    private final EventHandler<ResourceType, ResourceElement, CallbackEventHandler<ResourceElement>> handler;
    private final static ResourceBundle TXTBundle = TextResources.GUITextBundle;

    /**
     * Creates new form ProjectContentPane
     */
    public ProjectContentPane(SharedData data, EventHandler<ResourceType, ResourceElement, CallbackEventHandler<ResourceElement>> handler) {
        this.handler = handler;
        this.sharedData = data;
        initComponents();
        initDataListeners();
        initData();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        ResourceContextMenu = new javax.swing.JPopupMenu();
        RenameResource = new javax.swing.JMenuItem();
        RemoveResource = new javax.swing.JMenuItem();
        Sep1 = new javax.swing.JPopupMenu.Separator();
        ModifyResource = new javax.swing.JMenuItem();
        PaginaIstanze = new javax.swing.JPanel();
        PaginaOggetti = new javax.swing.JPanel();
        TreeScrollPane = new javax.swing.JScrollPane();
        ProjectTree = new javax.swing.JTree();
        StructLabel = new javax.swing.JLabel();
        AddLabel = new javax.swing.JLabel();
        AddButtonsContainer = new javax.swing.JPanel();
        AddFCButton = new javax.swing.JButton();
        AddFBButton = new javax.swing.JButton();
        AddDBButton = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        TitoloPannello = new javax.swing.JLabel();
        TabbedPane = new javax.swing.JTabbedPane();

        RenameResource.setText(TXTBundle.getString("Rename"));
        RenameResource.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RenameResourceActionPerformed(evt);
            }
        });
        ResourceContextMenu.add(RenameResource);

        RemoveResource.setText(TXTBundle.getString("Remove"));
        RemoveResource.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RemoveResourceActionPerformed(evt);
            }
        });
        ResourceContextMenu.add(RemoveResource);
        ResourceContextMenu.add(Sep1);

        ModifyResource.setText(TXTBundle.getString("EditResource"));
        ModifyResource.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ModifyResourceActionPerformed(evt);
            }
        });
        ResourceContextMenu.add(ModifyResource);

        javax.swing.GroupLayout PaginaIstanzeLayout = new javax.swing.GroupLayout(PaginaIstanze);
        PaginaIstanze.setLayout(PaginaIstanzeLayout);
        PaginaIstanzeLayout.setHorizontalGroup(
            PaginaIstanzeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 563, Short.MAX_VALUE)
        );
        PaginaIstanzeLayout.setVerticalGroup(
            PaginaIstanzeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 336, Short.MAX_VALUE)
        );

        ProjectTree.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ProjectTreeMouseClicked(evt);
            }
        });
        ProjectTree.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                ProjectTreeKeyPressed(evt);
            }
        });
        TreeScrollPane.setViewportView(ProjectTree);

        StructLabel.setText(TextResources.GUITextBundle.getString("ProjectStructure"));

        AddLabel.setText(TextResources.GUITextBundle.getString("AddElements"));

        AddFCButton.setText("FC");
        AddFCButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddFCButtonActionPerformed(evt);
            }
        });

        AddFBButton.setText("FB");
        AddFBButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddFBButtonActionPerformed(evt);
            }
        });

        AddDBButton.setText("DB");
        AddDBButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddDBButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout AddButtonsContainerLayout = new javax.swing.GroupLayout(AddButtonsContainer);
        AddButtonsContainer.setLayout(AddButtonsContainerLayout);
        AddButtonsContainerLayout.setHorizontalGroup(
            AddButtonsContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(AddButtonsContainerLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(AddFCButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(AddFBButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(AddDBButton)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        AddButtonsContainerLayout.setVerticalGroup(
            AddButtonsContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(AddButtonsContainerLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(AddButtonsContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(AddFCButton)
                    .addComponent(AddFBButton)
                    .addComponent(AddDBButton))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 305, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout PaginaOggettiLayout = new javax.swing.GroupLayout(PaginaOggetti);
        PaginaOggetti.setLayout(PaginaOggettiLayout);
        PaginaOggettiLayout.setHorizontalGroup(
            PaginaOggettiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PaginaOggettiLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(PaginaOggettiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PaginaOggettiLayout.createSequentialGroup()
                        .addGroup(PaginaOggettiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(StructLabel)
                            .addComponent(TreeScrollPane)
                            .addComponent(AddButtonsContainer, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(PaginaOggettiLayout.createSequentialGroup()
                        .addComponent(AddLabel)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        PaginaOggettiLayout.setVerticalGroup(
            PaginaOggettiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PaginaOggettiLayout.createSequentialGroup()
                .addGap(9, 9, 9)
                .addComponent(StructLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(PaginaOggettiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(TreeScrollPane, javax.swing.GroupLayout.DEFAULT_SIZE, 236, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(AddLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(AddButtonsContainer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        TitoloPannello.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        TitoloPannello.setText(TextResources.GUITextBundle.getString("ProjectContents"));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(TabbedPane)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(TitoloPannello)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(TitoloPannello)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(TabbedPane)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void ProjectTreeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ProjectTreeMouseClicked
        // TODO add your handling code here:
        if (evt.getButton() == MouseEvent.BUTTON3 && !ProjectTree.isSelectionEmpty()) {
            int x = evt.getX();
            int y = evt.getY();
            TreePath selectionPath = ProjectTree.getClosestPathForLocation(x, y);
            if (selectionPath == null) {
                selectionPath = ProjectTree.getSelectionPath();
            }
            ProjectTree.setSelectionPath(selectionPath);
            if (selectionPath == null) {
                return;
            }

            ProjectTree.getComponentPopupMenu().show(ProjectTree, x, y);
        }
    }//GEN-LAST:event_ProjectTreeMouseClicked

    private void RemoveResourceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RemoveResourceActionPerformed
        // TODO add your handling code here:
        if (!ProjectTree.isSelectionEmpty()) {
            TreePath selectionPath = ProjectTree.getSelectionPath();
            DefaultMutableTreeNode lastPathComponent = (DefaultMutableTreeNode) selectionPath.getLastPathComponent();
            Object obj = lastPathComponent.getUserObject();
            if (obj instanceof Project) {
                return;
            }
            ResourceElement re = (ResourceElement) obj;
            sharedData.removeResource(re);
        }
    }//GEN-LAST:event_RemoveResourceActionPerformed

    private void RenameResourceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RenameResourceActionPerformed
        ProjectTree.setEditable(true);
    }//GEN-LAST:event_RenameResourceActionPerformed

    private void ProjectTreeKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_ProjectTreeKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_F2) {
            ProjectTree.setEditable(true);
        }
    }//GEN-LAST:event_ProjectTreeKeyPressed

    private void AddFCButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddFCButtonActionPerformed
        handler.getSecureHandler(ResourceType.Function).callback(null);
    }//GEN-LAST:event_AddFCButtonActionPerformed

    private void AddFBButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddFBButtonActionPerformed
        handler.getSecureHandler(ResourceType.FunctionBlock).callback(null);
    }//GEN-LAST:event_AddFBButtonActionPerformed

    private void AddDBButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddDBButtonActionPerformed
        handler.getSecureHandler(ResourceType.DataBlock).callback(null);
    }//GEN-LAST:event_AddDBButtonActionPerformed

    private void ModifyResourceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ModifyResourceActionPerformed
        if (!ProjectTree.isSelectionEmpty()) {
            TreePath selectionPath = ProjectTree.getSelectionPath();
            DefaultMutableTreeNode lastPathComponent = (DefaultMutableTreeNode) selectionPath.getLastPathComponent();
            Object obj = lastPathComponent.getUserObject();
            if (obj instanceof Project) {
                return;
            }
            ResourceElement re = (ResourceElement) obj;
            if (re instanceof FunctionElement) {
                handler.getHandler(ResourceType.Function).callback(re);
            } else if (re instanceof FunctionBlockElement) {
                handler.getHandler(ResourceType.FunctionBlock).callback(re);
            } else if (re instanceof DataBlockElement) {
                handler.getHandler(ResourceType.DataBlock).callback(re);
            }
        }
    }//GEN-LAST:event_ModifyResourceActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel AddButtonsContainer;
    private javax.swing.JButton AddDBButton;
    private javax.swing.JButton AddFBButton;
    private javax.swing.JButton AddFCButton;
    private javax.swing.JLabel AddLabel;
    private javax.swing.JMenuItem ModifyResource;
    private javax.swing.JPanel PaginaIstanze;
    private javax.swing.JPanel PaginaOggetti;
    private javax.swing.JTree ProjectTree;
    private javax.swing.JMenuItem RemoveResource;
    private javax.swing.JMenuItem RenameResource;
    private javax.swing.JPopupMenu ResourceContextMenu;
    private javax.swing.JPopupMenu.Separator Sep1;
    private javax.swing.JLabel StructLabel;
    private javax.swing.JTabbedPane TabbedPane;
    private javax.swing.JLabel TitoloPannello;
    private javax.swing.JScrollPane TreeScrollPane;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables

    private void initDataListeners() {
        ProjectTree.setComponentPopupMenu(ResourceContextMenu);
        this.sharedData.addProjectOpenedEventListener((prj) -> {
            fillProjectTree(prj);
        });
        this.sharedData.addProjectEditedEventListener((prj) -> {
            fillProjectTree(prj);
        });
        ProjectTree.setCellEditor(new ProjectTreeEditor(ProjectTree));
        ProjectTree.getCellEditor().addCellEditorListener(new CellEditorListener() {
            @Override
            public void editingStopped(ChangeEvent e) {
                Pair<ResourceElement, String> re = (Pair<ResourceElement, String>) e.getSource();
                ProjectTree.setEditable(false);
                sharedData.renameResource(re.left(), re.right());
            }

            @Override
            public void editingCanceled(ChangeEvent e) {
                ProjectTree.setEditable(false);
            }
        });
    }

    private void initData() {
        fillProjectTree(this.sharedData.getProject());
        TabbedPane.addTab(TextResources.GUITextBundle.getString("Objects"), PaginaOggetti);
        TabbedPane.addTab(TextResources.GUITextBundle.getString("Istances"), PaginaIstanze);
    }

    private void fillProjectTree(Project prj) {
        DefaultMutableTreeNode root;
        DefaultTreeModel treeModel;
        root = new DefaultMutableTreeNode(prj, true);
        treeModel = new DefaultTreeModel(root);
        ProjectTree.setCellRenderer(new ProjectTreeRender());
        ProjectTree.setRootVisible(true);
        prj.getResources().values().forEach(map -> {
            map.forEach((string, element) -> {
                root.add(new DefaultMutableTreeNode(element));
            });
        });
        ProjectTree.setModel(treeModel);
        ProjectTree.setShowsRootHandles(true);
    }

}
